# Generated by Django 3.0.3 on 2021-08-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treater_feed', '0003_tweet_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Tweet_List',
        ),
    ]
